// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: settle.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SettleAction int32

const (
	SettleAction_Result  SettleAction = 0 // settle with result
	SettleAction_Cancel  SettleAction = 1 // Cancel
	SettleAction_RCancel SettleAction = 2 // RollbackCancel
	SettleAction_RSettle SettleAction = 3 // RollbackSettle
)

// Enum value maps for SettleAction.
var (
	SettleAction_name = map[int32]string{
		0: "Result",
		1: "Cancel",
		2: "RCancel",
		3: "RSettle",
	}
	SettleAction_value = map[string]int32{
		"Result":  0,
		"Cancel":  1,
		"RCancel": 2,
		"RSettle": 3,
	}
)

func (x SettleAction) Enum() *SettleAction {
	p := new(SettleAction)
	*p = x
	return p
}

func (x SettleAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SettleAction) Descriptor() protoreflect.EnumDescriptor {
	return file_settle_proto_enumTypes[0].Descriptor()
}

func (SettleAction) Type() protoreflect.EnumType {
	return &file_settle_proto_enumTypes[0]
}

func (x SettleAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SettleAction.Descriptor instead.
func (SettleAction) EnumDescriptor() ([]byte, []int) {
	return file_settle_proto_rawDescGZIP(), []int{0}
}

type OutcomeResultCode int32

const (
	OutcomeResultCode_OutcomeResult_Unknown     OutcomeResultCode = 0
	OutcomeResultCode_OutcomeResult_Open        OutcomeResultCode = 1
	OutcomeResultCode_OutcomeResult_Won         OutcomeResultCode = 2
	OutcomeResultCode_OutcomeResult_HalfWon     OutcomeResultCode = 3
	OutcomeResultCode_OutcomeResult_Lost        OutcomeResultCode = 4
	OutcomeResultCode_OutcomeResult_HalfLost    OutcomeResultCode = 5
	OutcomeResultCode_OutcomeResult_Void        OutcomeResultCode = 6
	OutcomeResultCode_OutcomeResult_Error       OutcomeResultCode = 7
	OutcomeResultCode_OutcomeResult_WonDeadHeat OutcomeResultCode = 8
	OutcomeResultCode_OutcomeResult_Cancel      OutcomeResultCode = 9
	OutcomeResultCode_OutcomeResult_Subpended   OutcomeResultCode = 10
)

// Enum value maps for OutcomeResultCode.
var (
	OutcomeResultCode_name = map[int32]string{
		0:  "OutcomeResult_Unknown",
		1:  "OutcomeResult_Open",
		2:  "OutcomeResult_Won",
		3:  "OutcomeResult_HalfWon",
		4:  "OutcomeResult_Lost",
		5:  "OutcomeResult_HalfLost",
		6:  "OutcomeResult_Void",
		7:  "OutcomeResult_Error",
		8:  "OutcomeResult_WonDeadHeat",
		9:  "OutcomeResult_Cancel",
		10: "OutcomeResult_Subpended",
	}
	OutcomeResultCode_value = map[string]int32{
		"OutcomeResult_Unknown":     0,
		"OutcomeResult_Open":        1,
		"OutcomeResult_Won":         2,
		"OutcomeResult_HalfWon":     3,
		"OutcomeResult_Lost":        4,
		"OutcomeResult_HalfLost":    5,
		"OutcomeResult_Void":        6,
		"OutcomeResult_Error":       7,
		"OutcomeResult_WonDeadHeat": 8,
		"OutcomeResult_Cancel":      9,
		"OutcomeResult_Subpended":   10,
	}
)

func (x OutcomeResultCode) Enum() *OutcomeResultCode {
	p := new(OutcomeResultCode)
	*p = x
	return p
}

func (x OutcomeResultCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutcomeResultCode) Descriptor() protoreflect.EnumDescriptor {
	return file_settle_proto_enumTypes[1].Descriptor()
}

func (OutcomeResultCode) Type() protoreflect.EnumType {
	return &file_settle_proto_enumTypes[1]
}

func (x OutcomeResultCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutcomeResultCode.Descriptor instead.
func (OutcomeResultCode) EnumDescriptor() ([]byte, []int) {
	return file_settle_proto_rawDescGZIP(), []int{1}
}

type OutcomeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Outcome uint64            `protobuf:"varint,1,opt,name=Outcome,proto3" json:"Outcome,omitempty"`                             // OutcomeId ID
	Result  OutcomeResultCode `protobuf:"varint,2,opt,name=Result,proto3,enum=settle.OutcomeResultCode" json:"Result,omitempty"` // settle result. check outcome result
	// if result = 8, check this field and "Won Dead Heat" settle logic
	Shared float64 `protobuf:"fixed64,3,opt,name=Shared,proto3" json:"Shared,omitempty"`
	// provide a array like [1,3], which producer need to settle
	Scope []uint32 `protobuf:"varint,4,rep,packed,name=Scope,proto3" json:"Scope,omitempty"`
}

func (x *OutcomeResult) Reset() {
	*x = OutcomeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutcomeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutcomeResult) ProtoMessage() {}

func (x *OutcomeResult) ProtoReflect() protoreflect.Message {
	mi := &file_settle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutcomeResult.ProtoReflect.Descriptor instead.
func (*OutcomeResult) Descriptor() ([]byte, []int) {
	return file_settle_proto_rawDescGZIP(), []int{0}
}

func (x *OutcomeResult) GetOutcome() uint64 {
	if x != nil {
		return x.Outcome
	}
	return 0
}

func (x *OutcomeResult) GetResult() OutcomeResultCode {
	if x != nil {
		return x.Result
	}
	return OutcomeResultCode_OutcomeResult_Unknown
}

func (x *OutcomeResult) GetShared() float64 {
	if x != nil {
		return x.Shared
	}
	return 0
}

func (x *OutcomeResult) GetScope() []uint32 {
	if x != nil {
		return x.Scope
	}
	return nil
}

type Settle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the settle result from which producer
	Producer uint32 `protobuf:"varint,1,opt,name=Producer,proto3" json:"Producer,omitempty"` // provide a array like [1,3], which producer need to settle
	// if SettleAction = Result, check the scope in OutcomeResult
	Scope []uint32 `protobuf:"varint,2,rep,packed,name=Scope,proto3" json:"Scope,omitempty"`
	// market ID,
	Market uint64 `protobuf:"varint,3,opt,name=Market,proto3" json:"Market,omitempty"`
	// cancel reason.
	Reason uint32 `protobuf:"varint,4,opt,name=Reason,proto3" json:"Reason,omitempty"`
	//
	// when SettleAction = Result
	// need to check the outcomes to settle thebet_selection
	Outcomes []*OutcomeResult `protobuf:"bytes,5,rep,name=Outcomes,proto3" json:"Outcomes,omitempty"`
	// Cancel  and RCancel  sometimes it will be provide, check the bet time
	From *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=From,proto3" json:"From,omitempty"`
	// Cancel  and RCancel  sometimes it will be provide, check the bet time
	To *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=To,proto3" json:"To,omitempty"`
}

func (x *Settle) Reset() {
	*x = Settle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Settle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settle) ProtoMessage() {}

func (x *Settle) ProtoReflect() protoreflect.Message {
	mi := &file_settle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settle.ProtoReflect.Descriptor instead.
func (*Settle) Descriptor() ([]byte, []int) {
	return file_settle_proto_rawDescGZIP(), []int{1}
}

func (x *Settle) GetProducer() uint32 {
	if x != nil {
		return x.Producer
	}
	return 0
}

func (x *Settle) GetScope() []uint32 {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Settle) GetMarket() uint64 {
	if x != nil {
		return x.Market
	}
	return 0
}

func (x *Settle) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *Settle) GetOutcomes() []*OutcomeResult {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

func (x *Settle) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Settle) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

//mq 消息结构
type SettleShell struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 结算消息的类型 结算 取消结算
	// this message for
	Action SettleAction `protobuf:"varint,1,opt,name=Action,proto3,enum=settle.SettleAction" json:"Action,omitempty"`
	// which markets need to process
	Settle []*Settle `protobuf:"bytes,2,rep,name=Settle,proto3" json:"Settle,omitempty"`
	// message created at
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *SettleShell) Reset() {
	*x = SettleShell{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SettleShell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleShell) ProtoMessage() {}

func (x *SettleShell) ProtoReflect() protoreflect.Message {
	mi := &file_settle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleShell.ProtoReflect.Descriptor instead.
func (*SettleShell) Descriptor() ([]byte, []int) {
	return file_settle_proto_rawDescGZIP(), []int{2}
}

func (x *SettleShell) GetAction() SettleAction {
	if x != nil {
		return x.Action
	}
	return SettleAction_Result
}

func (x *SettleShell) GetSettle() []*Settle {
	if x != nil {
		return x.Settle
	}
	return nil
}

func (x *SettleShell) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// check a seletion status
type OutcomeCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Producer uint32                 `protobuf:"varint,1,opt,name=Producer,proto3" json:"Producer,omitempty"`
	Market   uint64                 `protobuf:"varint,2,opt,name=Market,proto3" json:"Market,omitempty"`
	Outcome  uint64                 `protobuf:"varint,3,opt,name=Outcome,proto3" json:"Outcome,omitempty"`
	BetTime  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=BetTime,proto3" json:"BetTime,omitempty"`
}

func (x *OutcomeCheckRequest) Reset() {
	*x = OutcomeCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutcomeCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutcomeCheckRequest) ProtoMessage() {}

func (x *OutcomeCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutcomeCheckRequest.ProtoReflect.Descriptor instead.
func (*OutcomeCheckRequest) Descriptor() ([]byte, []int) {
	return file_settle_proto_rawDescGZIP(), []int{3}
}

func (x *OutcomeCheckRequest) GetProducer() uint32 {
	if x != nil {
		return x.Producer
	}
	return 0
}

func (x *OutcomeCheckRequest) GetMarket() uint64 {
	if x != nil {
		return x.Market
	}
	return 0
}

func (x *OutcomeCheckRequest) GetOutcome() uint64 {
	if x != nil {
		return x.Outcome
	}
	return 0
}

func (x *OutcomeCheckRequest) GetBetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BetTime
	}
	return nil
}

var File_settle_proto protoreflect.FileDescriptor

var file_settle_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x1a, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x0d, 0x4f, 0x75, 0x74, 0x63,
	0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x75, 0x74,
	0x63, 0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x4f, 0x75, 0x74, 0x63,
	0x6f, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x4f, 0x75, 0x74,
	0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x05, 0x53,
	0x63, 0x6f, 0x70, 0x65, 0x22, 0xf9, 0x01, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x53,
	0x63, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x12, 0x31, 0x0a, 0x08, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x4f, 0x75, 0x74,
	0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x08, 0x4f, 0x75, 0x74, 0x63,
	0x6f, 0x6d, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04,
	0x46, 0x72, 0x6f, 0x6d, 0x12, 0x2a, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x54, 0x6f,
	0x22, 0x9d, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x68, 0x65, 0x6c, 0x6c,
	0x12, 0x2c, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x14, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26,
	0x0a, 0x06, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x06,
	0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x22, 0x99, 0x01, 0x0a, 0x13, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x4f,
	0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x42, 0x65, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x07, 0x42, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x2a, 0x40, 0x0a, 0x0c,
	0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x10, 0x03, 0x2a, 0xb3,
	0x02, 0x0a, 0x11, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12,
	0x16, 0x0a, 0x12, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x5f, 0x4f, 0x70, 0x65, 0x6e, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x4f, 0x75, 0x74, 0x63, 0x6f,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x57, 0x6f, 0x6e, 0x10, 0x02, 0x12, 0x19,
	0x0a, 0x15, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f,
	0x48, 0x61, 0x6c, 0x66, 0x57, 0x6f, 0x6e, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x4f, 0x75, 0x74,
	0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x4c, 0x6f, 0x73, 0x74, 0x10,
	0x04, 0x12, 0x1a, 0x0a, 0x16, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x5f, 0x48, 0x61, 0x6c, 0x66, 0x4c, 0x6f, 0x73, 0x74, 0x10, 0x05, 0x12, 0x16, 0x0a,
	0x12, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x56,
	0x6f, 0x69, 0x64, 0x10, 0x06, 0x12, 0x17, 0x0a, 0x13, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x07, 0x12, 0x1d,
	0x0a, 0x19, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f,
	0x57, 0x6f, 0x6e, 0x44, 0x65, 0x61, 0x64, 0x48, 0x65, 0x61, 0x74, 0x10, 0x08, 0x12, 0x18, 0x0a,
	0x14, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x10, 0x09, 0x12, 0x1b, 0x0a, 0x17, 0x4f, 0x75, 0x74, 0x63, 0x6f,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x53, 0x75, 0x62, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x64, 0x10, 0x0a, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_settle_proto_rawDescOnce sync.Once
	file_settle_proto_rawDescData = file_settle_proto_rawDesc
)

func file_settle_proto_rawDescGZIP() []byte {
	file_settle_proto_rawDescOnce.Do(func() {
		file_settle_proto_rawDescData = protoimpl.X.CompressGZIP(file_settle_proto_rawDescData)
	})
	return file_settle_proto_rawDescData
}

var file_settle_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_settle_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_settle_proto_goTypes = []interface{}{
	(SettleAction)(0),             // 0: settle.SettleAction
	(OutcomeResultCode)(0),        // 1: settle.OutcomeResultCode
	(*OutcomeResult)(nil),         // 2: settle.OutcomeResult
	(*Settle)(nil),                // 3: settle.Settle
	(*SettleShell)(nil),           // 4: settle.SettleShell
	(*OutcomeCheckRequest)(nil),   // 5: settle.OutcomeCheckRequest
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_settle_proto_depIdxs = []int32{
	1, // 0: settle.OutcomeResult.Result:type_name -> settle.OutcomeResultCode
	2, // 1: settle.Settle.Outcomes:type_name -> settle.OutcomeResult
	6, // 2: settle.Settle.From:type_name -> google.protobuf.Timestamp
	6, // 3: settle.Settle.To:type_name -> google.protobuf.Timestamp
	0, // 4: settle.SettleShell.Action:type_name -> settle.SettleAction
	3, // 5: settle.SettleShell.Settle:type_name -> settle.Settle
	6, // 6: settle.SettleShell.Timestamp:type_name -> google.protobuf.Timestamp
	6, // 7: settle.OutcomeCheckRequest.BetTime:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_settle_proto_init() }
func file_settle_proto_init() {
	if File_settle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_settle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutcomeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_settle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Settle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_settle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SettleShell); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_settle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutcomeCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_settle_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_settle_proto_goTypes,
		DependencyIndexes: file_settle_proto_depIdxs,
		EnumInfos:         file_settle_proto_enumTypes,
		MessageInfos:      file_settle_proto_msgTypes,
	}.Build()
	File_settle_proto = out.File
	file_settle_proto_rawDesc = nil
	file_settle_proto_goTypes = nil
	file_settle_proto_depIdxs = nil
}
